Repository cmput301-w25/project-cachecows, pull requests merged in 2025-03, with the labels that each got.

#136 Implemented image compression/resizing
  code/Feelink/app/src/main/java/com/example/feelink/MoodEventAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/UploadImageActivity.java
  code/Feelink/app/src/main/res/drawable/bg_white_gray.xml
  code/Feelink/app/src/main/res/layout/add_mood_event.xml
  code/Feelink/app/src/main/res/layout/dialog_mood_details.xml
  code/Feelink/app/src/main/res/layout/item_mood_event.xml
  code/Feelink/app/src/main/res/values/colors.xml
Labels: Project Part 3

#177 US 07: Offline Behavior
  code/Feelink/app/build.gradle.kts
  code/Feelink/app/src/main/assets/loading2.json
  code/Feelink/app/src/main/assets/loading_animation.json
  code/Feelink/app/src/main/java/com/example/feelink/AddMoodEventActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/ConnectivityReceiver.java
  code/Feelink/app/src/main/java/com/example/feelink/FeedManagerActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/FirestoreManager.java
  code/Feelink/app/src/main/java/com/example/feelink/MainActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/MoodEvent.java
  code/Feelink/app/src/main/java/com/example/feelink/MoodEventAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/PendingSyncManager.java
  code/Feelink/app/src/main/res/layout/activity_feed_manager.xml
  code/Feelink/app/src/main/res/layout/item_mood_event.xml
  code/Feelink/app/src/main/res/values/colors.xml
  code/Feelink/app/src/main/res/values/strings.xml
  code/Feelink/gradle/libs.versions.toml
Labels: task, Project Part 4

#184 Expanded on User Story 7: Now Photos Can Be Upploaded Offline
  code/Feelink/app/src/main/java/com/example/feelink/AddMoodEventActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/ConnectivityReceiver.java
  code/Feelink/app/src/main/java/com/example/feelink/FirestoreManager.java
  code/Feelink/app/src/main/java/com/example/feelink/MoodEventAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/UploadImageActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/UserProfileActivity.java
  code/Feelink/app/src/main/res/layout/activity_feed_manager.xml
  code/Feelink/app/src/main/res/layout/activity_user_profile.xml
Labels: task, Project Part 4

#187 Some Major UI changes
  code/Feelink/app/src/main/AndroidManifest.xml
  code/Feelink/app/src/main/java/com/example/feelink/ChatActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/CommentAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/ConversationsAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/CreateAccount.java
  code/Feelink/app/src/main/java/com/example/feelink/FirestoreManager.java
  code/Feelink/app/src/main/java/com/example/feelink/MoodEvent.java
  code/Feelink/app/src/main/java/com/example/feelink/MoodEventAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/NotificationAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/NotificationsActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/UploadProfilePictureActivity.java
  code/Feelink/app/src/main/res/drawable/back_button.xml
  code/Feelink/app/src/main/res/drawable/bg_bottom_bar_chat.xml
  code/Feelink/app/src/main/res/drawable/bg_chat_gradient.xml
  code/Feelink/app/src/main/res/drawable/circle_background.xml
  code/Feelink/app/src/main/res/drawable/ic_mood_confused.xml
  code/Feelink/app/src/main/res/drawable/ic_mood_surprised.xml
  code/Feelink/app/src/main/res/drawable/ic_nav_chats.xml
  code/Feelink/app/src/main/res/drawable/ic_nav_home.xml
  code/Feelink/app/src/main/res/drawable/ic_nav_profile.xml
  code/Feelink/app/src/main/res/drawable/ic_profile_placeholder.png
  code/Feelink/app/src/main/res/drawable/ic_send.xml
  code/Feelink/app/src/main/res/drawable/message_bg_received.xml
  code/Feelink/app/src/main/res/drawable/message_bg_sent.xml
  code/Feelink/app/src/main/res/drawable/rounded_bubble.xml
  code/Feelink/app/src/main/res/layout/activity_chat.xml
  code/Feelink/app/src/main/res/layout/activity_comments.xml
  code/Feelink/app/src/main/res/layout/activity_conversations_list.xml
  code/Feelink/app/src/main/res/layout/activity_create_account.xml
  code/Feelink/app/src/main/res/layout/activity_feed_manager.xml
  code/Feelink/app/src/main/res/layout/activity_notifications.xml
  code/Feelink/app/src/main/res/layout/activity_search.xml
  code/Feelink/app/src/main/res/layout/activity_upload_image.xml
  code/Feelink/app/src/main/res/layout/activity_upload_profile_image.xml
  code/Feelink/app/src/main/res/layout/activity_user_profile.xml
  code/Feelink/app/src/main/res/layout/add_mood_event.xml
  code/Feelink/app/src/main/res/layout/item_comment.xml
  code/Feelink/app/src/main/res/layout/item_conversation.xml
  code/Feelink/app/src/main/res/layout/item_message_received.xml
  code/Feelink/app/src/main/res/layout/item_message_sent.xml
  code/Feelink/app/src/main/res/layout/item_mood_event.xml
  code/Feelink/app/src/main/res/layout/item_notification.xml
  code/Feelink/app/src/main/res/layout/item_search_result.xml
  code/Feelink/app/src/main/res/layout/other_user_profiles.xml
  code/Feelink/app/src/main/res/layout/search_users_layout.xml
Labels: enhancement

#198 Some tests need correction
  code/.DS_Store
  code/Feelink/app/build.gradle.kts
  code/Feelink/app/src/androidTest/java/com/example/feelink/AddMoodEventTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/CommentsActivityTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/LoginActivityTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/MapFunctionalityTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/SearchFunctionalityTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/UserProfileEmotionFilterTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/UserProfilePrivateMoodsTest.java
  code/Feelink/app/src/main/java/com/example/feelink/AddMoodEventActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/FirestoreManager.java
  code/Feelink/app/src/main/java/com/example/feelink/LocationPickerActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/MoodMapActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/OtherUserProfileActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/User.java
  code/Feelink/app/src/main/java/com/example/feelink/UserAdapter.java
  code/Feelink/app/src/main/java/com/example/feelink/UserProfileActivity.java
  code/Feelink/app/src/main/res/layout/activity_user_profile.xml
  code/Feelink/app/src/main/res/layout/dialog_mood_details.xml
  code/Feelink/app/src/main/res/layout/item_mood_event.xml
  code/Feelink/app/src/main/res/layout/other_user_profiles.xml
  code/Feelink/app/src/main/res/layout/search_users_layout.xml
  code/Feelink/app/src/main/res/layout/user_item.xml
  code/Feelink/firebase.json
Labels: Project Part 4, tests

#200 some more ui tests
  code/Feelink/app/src/androidTest/java/com/example/feelink/AddMoodEventActivityTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/AddMoodEventTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/FeedManagerOfflineBehaviorTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/LoginActivityTest.java
  code/Feelink/app/src/androidTest/java/com/example/feelink/MapFunctionalityTest.java
  code/Feelink/app/src/main/java/com/example/feelink/view/ChatActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/view/FeedManagerActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/view/LocationPickerActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/view/MoodMapActivity.java
  code/Feelink/app/src/main/java/com/example/feelink/view/UserProfileActivity.java
Labels: tests
